using Microsoft.Extensions.DependencyInjection;

namespace KaxamlPlugins.DependencyInjection.Registration;

/// <summary>
/// Registers a Service Type with a DI Service that is generated by a provider method.
/// </summary>
/// <param name="Factory">Provider method to generate the Type when called for</param>
/// <typeparam name="TService">Type of source to be registered</typeparam>
public sealed record FactoryDiRegistration<TService>(
    Func<IServiceProvider, TService> Factory) : IDiRegistration
    where TService : class
{
    public void RegisterSingleton(IServiceCollection services)
        => services.AddSingleton(Factory);
}